$files = @(
    'js/utils.js',
    'js/store.js',
    'js/seed.js',
    'js/modules/vehicles.js',
    'js/modules/drivers.js',
    'js/modules/trips.js',
    'js/modules/fuel.js',
    'js/modules/expenses.js',
    'js/modules/reports.js',
    'js/modules/maintenance.js',
    'js/modules/tracking.js',
    'js/modules/settings.js',
    'js/app.js'
)

$outputFile = 'js/bundle.js'

$header = @"
/* BUNDLED JS - Generated by PowerShell */

// Global Error Handler
window.onerror = function(msg, url, line, col, error) {
    console.error('Global Error:', msg, 'Line:', line, error);
    return false;
};
"@

$combined = $header

foreach ($file in $files) {
    if (Test-Path $file) {
        Write-Host "Processing $file"
        $content = Get-Content $file -Raw
        # Remove imports
        $content = $content -replace 'import\s+.*', ''
        # Remove exports
        $content = $content -replace 'export\s+const', 'const'
        $content = $content -replace 'export\s+default', ''
        
        $combined += "`n`n/* --- SOURCE: $file --- */`n"
        $combined += $content
    }
    else {
        Write-Error "File not found: $file"
    }
}

$combined | Set-Content $outputFile -Encoding UTF8
Write-Host "Bundle created at $outputFile"
